#!/bin/bash

#RSF, rfrase03@uoguelph.ca
#Script functions to convert the raw, compressed data generated by the MiSeq into uncompressed files with human-readable filenames.

compressed_dir=/media/russ/data/bovine/2015_12_13/1_compressed/*
uncompressed_dir=/media/russ/data/bovine/2015_12_13/2_uncompressed



echo Copying and decompressing fastq files...
 
for file in $compressed_dir
do
 	echo $file
 	cp $file $uncompressed_dir
done
echo done.

echo Giving files normal names...
for strange_name in "$uncompressed_dir"/*
do
	gunzip $strange_name
	strange_name="${strange_name%.gz}"
	base="${strange_name%_S*}" #should equal the group number
	base="${base#$uncompressed_dir/}"
	echo $base
	read="${strange_name%_001.fastq}" #should now equal (group number)_S10_L001_R(read direction)
	read="${read#*_L001_R}" #should equal the read direction
	mv $strange_name "$uncompressed_dir"/"$base"r"$read".fastq
done
echo done.